from math_is_fun import get_hex_points
from math_is_fun import get_hex_area
from math_is_fun import get_random_vector
from math_is_fun import get_random_angle
from math_is_fun import get_distance_within
from math_is_fun import get_average_vector
from math_is_fun import get_segment_of_line
